name: Release pipeline

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  release-pipeline:

    environment: "PROD"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_PROD_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: setup.py

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install -r unit-requirements.txt
          pip install -e .

      - name: Deploy PROD-demo-classifier-feature-table-refresh job [prod environment]
        run: |
          dbx deploy --deployment-file conf/deployment.yml PROD-demo-classifier-feature-table-refresh --environment=prod

      - name: Deploy PROD-demo-classifier-model-train job [prod environment]
        run: |
          dbx deploy --deployment-file conf/deployment.yml PROD-demo-classifier-model-train --environment=prod

      - name: Deploy PROD-demo-classifier-model-deployment job [prod environment]
        run: |
          dbx deploy --deployment-file conf/deployment.yml PROD-demo-classifier-model-deployment --environment=prod

      - name: Deploy PROD-demo-classifier-model-inference-batch job [prod environment]
        run: |
          dbx deploy --deployment-file conf/deployment.yml PROD-demo-classifier-model-inference-batch --environment=prod

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Release for version ${{ github.ref }}.
          draft: false
          prerelease: false